### ISSUE TITLE
Does not work on emacs 25

### ISSUE THREAD

**Issue by sahlhoff** [atykhonov/escr#1]
Escr creates a directory but does not write a file to it. I have import as a global command.

Is there a way I can debug this?

Thanks.

**Comment by atykhonov** [comment]
Hi!

As the first step, you can check whether Emacs could create a screenshot at all:

```
M-: (frame-parameter (selected-frame) 'window-id) RET
```

You'll get `window-id`. Use it in the following expression (instead of `31457296`):

```
(call-process "import" nil nil nil
              "-window" "31457296"
              "-crop" "1000x1000+0+0"
              (expand-file-name "~/.emacs.d/screenshots/test.png"))
```
As the successful result, you should see in the echo area:

```
0 (#o0, #x0, ?\C-@)
```

I'm not sure what does mean everything after `0`. But `0` means exit code. If you get `1` instead, then program exists with an error. If you'll get `1`, then please try execute the following **in the shell** and while it waits 5 seconds make your Emacs window active:

(please insert your `window-id` instead of `31457296`)

```
sleep 5 && import -window 31457296 -crop 1000x1000+0+0 ~/.emacs.d/screenshots/test.png
```

Check the output (let me know please what you'll get), and hopefully you'll get the answer what exactly is wrong.

**Comment by sahlhoff** [comment]
Awesome, I'll give this a try and report back.
